### ISSUE TITLE
dev.json

### ISSUE THREAD

**Issue by huimoran** [BeachWang/DAIL-SQL#10]
Hello, I saw that in your code, "train_spider_and_others.json" and "train_others.json" were merged to get train_spider_and_others. Would you like to ask if you used all the spider data sets in your paper, or just the dev.json data set?

![dail](https://github.com/BeachWang/DAIL-SQL/assets/100472413/464b1fe5-4d06-4317-a6b1-a31555007b40)

I see that the default data in generate_question.py uses dev.json

![dev](https://github.com/BeachWang/DAIL-SQL/assets/100472413/29854988-8be8-4ac3-bdb8-6b125a2ba17d)

Did you train the model using train_spider_and_others and then test it using dev.json?

**Comment by BeachWang** [comment]
Hi,
We did not train the model with train_spider_and_others. We used train_spider_and_others as the example candidates and chose the examples from the candidates in few-shot cases of prompt engineering to leverage the capacity of in-context learning of LLMs.
