### ISSUE TITLE
question.json + pre_test_result [your_pre_generated_queries_file]

### ISSUE THREAD

**Issue by nickgannon10** [BeachWang/DAIL-SQL#11]
[UPDATE] Nevermind, your_pre_generated_queries_file is already included at ./results/DAIL-SQL+GPT-4.txt

I hope all is well, I'm attempting to re-implement this research paper, and I was wondering if there is any chance that you have a pre_generated_queries file that I could use to do some testing of the functionality. If not, no worries. Thanks and the paper is awesome, great work!

 
python generate_question.py \
--data_type spider \
--split test \
--tokenizer gpt-3.5-turbo \
--max_seq_len 4096 \
--selector_type EUCDISMASKPRESKLSIMTHR \
--pre_test_result [your_pre_generated_queries_file] \
--prompt_repr SQL \
--k_shot 9 \
--example_type QA

**Comment by BeachWang** [comment]
Thank you very much.
We take [Graphix](https://github.com/AlibabaResearch/DAMO-ConvAI/tree/main/graphix) as our preliminary model in our experiments in the paper. We have upload the your_pre_generated_queries_file in results/graphix_result.txt for Spider dev.

**Comment by nickgannon10** [comment]
Thank you, this is super helpful. I really appreciate it!
