### ISSUE TITLE
Database schema

### ISSUE THREAD

**Issue by huimoran** [BeachWang/DAIL-SQL#12]
Hello, I would like to ask, in the text2sql experiment,
 is your database schema bound with natural language (referring to the question based on the database schema), 
or is the natural language question independent of the database schema (according to the natural language question to find the matching database schema into the corresponding prompt)?

**Comment by BeachWang** [comment]
Good questions!
In Spider and BIRD datasets, the database schema is bound with natural language. However, it is more common in practical applications that the natural language question is independent with the database schema. It is one of the key points to identify the corresponding database schema in numerous tables in applications of Text2SQL.
