### ISSUE TITLE
Script or code for evaluation?

### ISSUE THREAD

**Issue by behroozazarkhalili** [BeachWang/DAIL-SQL#13]
Hi,
I would appreciate it if you could provide me with the evaluation script since there is no information about it in the repository. Although I am aware that you use some other packages for evaluation, I am not sure how you utilized them to assess the results.

**Comment by mokeyish** [comment]
@BeachWang +1

**Comment by BeachWang** [comment]
Hi,
Please refer to the [Test Suites](https://github.com/taoyds/test-suite-sql-eval) for the evaluation metrics. We adopt the “Test Suite Execution Accuracy with Values” in the evaluation project.
