### ISSUE TITLE
open-source for BIRD dataset?

### ISSUE THREAD

**Issue by BugMaker-Boyan** [BeachWang/DAIL-SQL#14]
Thanks for your nice work.

Can you open source code & dev-predicted-sqls for re-implement BIRD dataset? I cannot find related code in this repo.

Thanks.

**Comment by jind11** [comment]
+1

**Comment by BeachWang** [comment]
Hi,

We have upload the code for BIRD dataset. Please put the train and dev split of BIRD in `./dataset/bird` and run `run_for_bird.sh`.

BTW, we set the query similarity threshold from 0.85 to 0.8 in `prompt/ExampleSelectorTemplate.py` when submitting DAIL-SQL to the BIRD leaderboard.

**Comment by BugMaker-Boyan** [comment]
Thanks for your response!
