### ISSUE TITLE
issue with generate_question.py

### ISSUE THREAD

**Issue by larissa0898** [BeachWang/DAIL-SQL#15]
Hi there!
I was initially implementing DAIL-SQL, and the version I pulled at the beginning of December worked perfectly fine. However, with the new commits and the updated version, I'm encountering the following error when I run this command:
```bash
python generate_question.py \
-- data_type spider \
--split test \
--tokenizer gpt-3.5-turbo \
--max_seq_len 4096 \
--prompt_repr SQL \
--k_shot 9 \
--example_type QA \
--selector_type  EUCDISQUESTIONMASK
```

Error:
```bash
File "generate_question.py", line 29, in <module>
    REPR_TYPE.OPENAI_DEMOSTRATION_WFK,
AttributeError: type object 'REPR_TYPE has no attribute  'OPENAI_DEMOSTRATION_WFK'
```

**Comment by BeachWang** [comment]
Thank you very much.
This bug is induced by the renaming of the question representations in `enums.py`. I have fixed them.
