### ISSUE TITLE
pre_test_results BIRD-SQL

### ISSUE THREAD

**Issue by nickgannon10** [BeachWang/DAIL-SQL#16]
Hi, 

Like BugMaker-Boyan, I'm super grateful that you have added the BIRD-SQL results -- it's definitely the best benchmark in Text-to-SQL right now. 

I'm strapped for compute at the moment (aren't we all), and don't think I can afford to run the pre_test_result generation phase.

I want to check that the url below, contains the pre_test_results you used to Bird-SQL. 

https://github.com/AlibabaResearch/DAMO-ConvAI/blob/main/bird/llm/exp_result/turbo_output_kg/predict_dev.json  

If they are not the correct pre_test_results, I was wondering if you could release the pre_test_results you originally generated, similar to the results/graphix_result.txt for Spider dev? 

I'm excited to see what you and your team do next!

**Comment by BeachWang** [comment]
Hi,

The `results/graphix_result.txt ` was used for the detailed experiments in Spider Dev. We did not run much experiments in BIRD and just got the pre_test_result via GPT-4. Please refer `run_for_bird.sh` to produce the pre_test_result via GPT-4 with following commands:
```
python ask_llm.py \
--openai_api_key $1 \
--model gpt-4 \
--question ./dataset/process/BIRD-TEST_SQL_7-SHOT_EUCDISQUESTIONMASK_QA-EXAMPLE_CTX-200_ANS-4096/ \
--db_dir ./dataset/bird/databases
```
We have uploaded the pre_test_result in `results/QUESTIONMASK_GPT-4_for_bird.txt`.

**Comment by nickgannon10** [comment]
Thank you will do!
