### ISSUE TITLE
NameError in data_preprocess.py

### ISSUE THREAD

**Issue by hsswiki** [BeachWang/DAIL-SQL#18]
https://github.com/BeachWang/DAIL-SQL/blob/d78ce3466f9863b16001059b928a32d78cbec1c8/data_preprocess.py#L112

Need to add `data_type = args.data_type` in the previous line to avoid the following error:

Traceback (most recent call last):
  File "data_preprocess.py", line 112, in <module>
    if data_type == "spider":
NameError: name 'data_type' is not defined

**Comment by BeachWang** [comment]
Have fixed it. Thank you very much!
