### ISSUE TITLE
Did you use Spider-dev as the examples set when evaluate Spider-test

### ISSUE THREAD

**Issue by wasedawesley** [BeachWang/DAIL-SQL#19]
hi，thanks for sharing DAIl-SQL codes. 
We notice the improvements by DAIL demo selection(EuclideanDistanceQuestionMaskPreSkeletonSimilarThresholdSelector)

Here is my question:
When evaluating at Spider-Test,  did you add Spider-dev into the demo sets?

**Comment by BeachWang** [comment]
Hi,
We only use the Spider-Train as the demo sets when evaluating at Spider-Test.
