### ISSUE TITLE
the process of generating the jsonl file 

### ISSUE THREAD

**Issue by mimi19997118** [BeachWang/DAIL-SQL#22]
Hello, first of all I would like to congratulate you for the great work! I have been focusing on the code but I am having difficulties in understanding the process and steps in order to generate the jsonl file of spider data of test_schema_linking and train_schema_linking,  could you help me in this ?

**Comment by BeachWang** [comment]
Hi,

Thank you for your focusing. The test_schema_linking and train_schema_linking are used for Masked Question Similarity Selection for in-context learning. We consider the cross-domain Text-to-SQL, which means problems have different database schemas in the training set and dev set . In cross-domain Text-to-SQL, we can achieve more reliable question match between the dev and training and select more suitable example from training set, if we mask the schema-related tokens in questions. You can refer to our paper (https://arxiv.org/abs/2308.15363) for more detail.
