### ISSUE TITLE
Can you provide the pre-generated SQL query dataset？

### ISSUE THREAD

**Issue by TingweiPei** [BeachWang/DAIL-SQL#29]
ChatGPT4 API calls are expensive, can you provide the pre-generated SQL query dataset which is generated  by GPT-4 for EUCDISMASKPRESKLSIMTHR？

**Comment by BeachWang** [comment]
Hi,

You can get them in the following CodaLab links:
https://worksheets.codalab.org/bundles/0x1204f43b05de4c829bea2af8cb7f48ae
https://worksheets.codalab.org/bundles/0x064cfc6c8e884aa0acaa5ee483bba5e4
