### ISSUE TITLE
zero-shot results for bird 

### ISSUE THREAD

**Issue by nnarodytska** [BeachWang/DAIL-SQL#31]
Dear All,

Would it be possible to share zero-shot results for bird dataset? 

Thank you!

**Comment by BeachWang** [comment]
Hi,

Thank you for your interest. DAIL-SQL is a method to leverage the in-context-learning capacity of LLM. Our ablation studies are mainly based on the Spider dataset. So I am sorry about that we have no the results on zero-shot scenario for Bird dataset.

Thanks!

**Comment by nnarodytska** [comment]
Got it, thank you for the reply!
