### ISSUE TITLE
Help wanted! Question about the `run_for_bird.sh`.

### ISSUE THREAD

**Issue by kanseaveg** [BeachWang/DAIL-SQL#33]
In the `run_for_bird.py`, I find two pieces of code that may have similar functionality, what is the difference between them?

![image](https://github.com/BeachWang/DAIL-SQL/assets/80022154/4694a3ab-86a5-4963-b759-0cc154a57ac9)

BTW, If the following section code is used, will the 02_ask_chatgpt.py code file be open source?

**Comment by BeachWang** [comment]
Hi,

Thank you for pointing out the discrepancy. The file name `02_ask_chatgpt.py` mentioned earlier is indeed incorrect; the correct file name is `ask_llm.py`.

Regarding the DAIL-SQL methodology, it incorporates two types of similarities for selecting samples: question-mask similarity and predicted-query similarity. To clarify the process: In lines 3 to 11 of the script, we are specifically selecting samples based on the question-mask similarity. Once these samples are chosen, we generate the predicted queries for them. Subsequently, in lines 13 to 22, we refine our sample selection by considering both question-mask similarity and predicted-query similarity. This dual similarity approach helps in further narrowing down the most relevant samples.

By employing this two-step similarity assessment, DAIL-SQL ensures the selection of samples that are more likely to yield accurate and pertinent predicted queries. If you have any more questions or need further assistance, please feel free to ask.

**Comment by kanseaveg** [comment]
Thank you for your answer.
