### ISSUE TITLE
About processed data

### ISSUE THREAD

**Issue by Z-Diviner** [BeachWang/DAIL-SQL#34]
Hello, it's an honor to read your paper, which has inspired me deeply. When downloading your preprocessed data, I found the following four files, representing examples of how they were processed. Can you help me explain them?
![image](https://github.com/BeachWang/DAIL-SQL/assets/130019806/d7a43363-25e5-44bc-b817-8f764944e0f8)

**Comment by Z-Diviner** [comment]
And could you provide some information about the data processed on the Bird dataset？

**Comment by BeachWang** [comment]
Hi, thank you for your interest in our paper. 

The EUCDISQUESTIONMASK implies that the application of selector with only masked question similarity. The EUCDISMASKPRESKLSIMTHR considers the both similarities of masked question and the skeleton of pre-predicted SQL. The QA says we represent examples with questions and queries, and without database schemas. The 150 is the limit of output length of LLM, while 10000 and 4096 are the limit of total length.

**Comment by BeachWang** [comment]
> And could you provide some information about the data processed on the Bird dataset？

Sorry, I don't quite understand your request. Are you in need of the intermediate results from the Bird dataset?
