### ISSUE TITLE
About preliminary model graphix

### ISSUE THREAD

**Issue by Zqzqsb** [BeachWang/DAIL-SQL#36]
I have read your paper and replicated your experiment, but there's something I don't quite understand. Perhaps I missed it, but could you please point out to me how the preliminary model graphix is introduced in your code? I would greatly appreciate it!

**Comment by BeachWang** [comment]
Thank you for your interest in our work. It is just because I happen to know one of the authors of Graphix personally, and I can obtain the necessary results directly from them to facilitate our experiments.

**Comment by kanseaveg** [comment]
However, it seems they haven't provided the code for running Graphix-T5 on Bird. I would like to inquire how DAIL-SQL utilizes Graphix-T5 as a pre-generation model for reproduction?

**Comment by BeachWang** [comment]
I asked my friend to run a result on BIRD as well : )

Besides, I want to clarify that Graphix-T5 can be replaced with any other moderately performing model, Even the LLM itself.

**Comment by kanseaveg** [comment]
![image](https://github.com/BeachWang/DAIL-SQL/assets/80022154/cdafa6e1-f44c-416a-b985-8395b8d2107c)
This WeChat number, with the profile picture of your friend, is regrettably no longer being updated as he mentioned.😭

**Comment by BeachWang** [comment]
> ![image](https://private-user-images.githubusercontent.com/80022154/336430057-cdafa6e1-f44c-416a-b985-8395b8d2107c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1MDEwNDksIm5iZiI6MTcxNzUwMDc0OSwicGF0aCI6Ii84MDAyMjE1NC8zMzY0MzAwNTctY2RhZmE2ZTEtZjQ0Yy00MTZhLWI5ODUtODM5NWI4ZDIxMDdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA0VDExMzIyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2Y2ZiZTM4NjIxYTlkNTU5NTU1YmNmOGFjZjc1YTQ5MTQ1NzVlMGY4YTc3MzYwN2QyYTAxZGM2NzM2NGVmZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.u6iEe0iCvP_YP_7bS13DaEXXQzFi6pVdsYSCURhximo) This WeChat number, with the profile picture of your friend, is regrettably no longer being updated as he mentioned.😭

I'm sorry, I remembered incorrectly. We only run experiments with Graphix-T5 on Spider and Spider realistic, but not on Bird. We only run experiments with GPT-4 as the preliminary model on Bird.

**Comment by kanseaveg** [comment]
never mind.

**Comment by BeachWang** [comment]
I have uploaded the experiment results on BIRD dev with GPT-4 as the preliminary model to `results`.
