### ISSUE TITLE
What is the purpose of "data_preprocess.py"

### ISSUE THREAD

**Issue by Cha-01** [BeachWang/DAIL-SQL#38]
I am a little dizzy about "data_preprocess.py". Could u please tell me roughly how it works？

**Comment by BeachWang** [comment]
Hi,

Thank you for your interest in our code. The `data_preprocess.py` has two functions: 

1. Data format conversion; 
3. Schema-linking, which links tokens related to the database mentioned in the question, such as table names, column names, or values in cells.

**Comment by Cha-01** [comment]
Thanks!
