### ISSUE TITLE
How do you verify the answer?

### ISSUE THREAD

**Issue by Sherlocktein** [BeachWang/DAIL-SQL#40]
I have now generated an SQL file, so how do I verify its accuracy, and what should I do?

**Comment by marcocastiglia** [comment]
You should refer to the Test Suites available at [this repository](https://github.com/taoyds/test-suite-sql-eval), which provides the new standard for evaluating Spider dataset. 
Kindly review the issues reported in that repository, as I encountered and had to address certain bugs to ensure the code ran correctly.
