### ISSUE TITLE
Issues in reproducing your results

### ISSUE THREAD

**Issue by marcocastiglia** [BeachWang/DAIL-SQL#41]
Hello,
I am currently working on my master's thesis and am highly interested in your research. I am attempting to reproduce your results and have used the following parameters to generate the questions:

"args": {
    "data_type": "spider",
    "split": "test",
    "k_shot": 5,
    "prompt_repr": "SQL",
    "example_type": "QA",
    "selector_type": "EUCDISMASKPRESKLSIMTHR",
    "max_seq_len": 4096,
    "max_ans_len": 200,
    "tokenizer": "gpt-3.5-turbo",
    "scope_factor": 100,
    "pre_test_result": "results/graphix_result.txt"
}

I am utilizing the GPT-3.5-turbo model to generate SQL queries. In evaluating exact match and execution accuracy using test suites, I have obtained the following results:

Exact match: 0.6228239845261122
Execution accuracy: 0.6972920696324951

When using the parameter "selector_type": "EUCDISPRESKLSIMTHR", the results are slightly different:

Exact match: 0.6199226305609284
Execution accuracy: 0.7166344294003868

I have also tried with k-shot: 9, however the results are pretty similar.

Could you please provide any solutions or suggestions to help me achieve results closer to yours using the GPT-3.5-turbo model?

Thank you for your time and assistance.

Best regards,

**Comment by BeachWang** [comment]
Hello,

Apologies for my delayed response. Have you utilized the [test-suite-sql-eval](https://github.com/taoyds/test-suite-sql-eval) for evaluating the result?

**Comment by marcocastiglia** [comment]
Yes, I am using test-suite-sql-eval for evaluating the result.
Can you please share, if possible, all the needed parameters and info in order to obtain the best results using gpt-3.5-turbo as in your paper?
Thank you so much in advance.
