### ISSUE TITLE
Switching GPT to Affordable Domestic Models for Research

### ISSUE THREAD

**Issue by zhangnianlong** [BeachWang/DAIL-SQL#45]
Hi
Hello, I am a graduate student who wants to conduct some scientific research based on DAIL-SQL. However, GPT is too costly, so I would like to inquire about how to switch GPT to qwen or other large domestic models. Thank you.

**Comment by BeachWang** [comment]
Thank you for your attention. You can add an API call function similar with the functions in [chatgpt.py](https://github.com/BeachWang/DAIL-SQL/blob/main/llm/chatgpt.py).
