### ISSUE TITLE
Error During Data Processing

### ISSUE THREAD

**Issue by realningzheng** [BeachWang/DAIL-SQL#5]
Hi! 

Thanks for the great work! I followed the instructions in the readme but got no lock while running `python data_preprocess.py`

It stucks at "test section linking: " at 0%. Any clues on what could be the possible reason?

Thanks a lot!

**Comment by BeachWang** [comment]
Hi,

Have you launch the coreNLP server?

**Comment by belugak** [comment]
Hi！

It seems that we have the same problem, did you resolve this problem? If so please tell me how to resolve it, Thanks a lot.

**Comment by BeachWang** [comment]
Have you launch the coreNLP server via the following command?
```
apt install default-jre
apt install default-jdk
cd third_party/stanford-corenlp-full-2018-10-05
nohup java -mx4g -cp "*" edu.stanford.nlp.pipeline.StanfordCoreNLPServer &
cd ../../
```

**Comment by BeachWang** [comment]
By the way, you need to put the third_party dir just under the DAIL-SQL project. Please see the line 36 in `/utils/linking_utils/corenlp.py`.
