### ISSUE TITLE
Why the execution accuracy in spider-dev dataset is different from the paper?

### ISSUE THREAD

**Issue by Apricity-lxy** [BeachWang/DAIL-SQL#6]
I eval the spider-dev using official test-suit-sql-eval scripts, with the GPT-4 results in your repo, but the execution accuracy is different.

The paper result: 83.5%

But I get: 76.2

run cmd:

python3 evaluation.py --gold ./my_test/gold_sqls.txt --pred ./my_test/DAIL-SQL+GPT-4+self-consistency.txt --db ./database/database/ --etype exec

                     easy                 medium               hard                 extra                all                 
count                248                  446                  174                  166                  1034                
=====================   EXECUTION ACCURACY     =====================
execution            0.903                0.818                0.661                0.506                0.762

**Comment by BeachWang** [comment]
Hi,
Do you use the last [test-suite-sql-eval](https://github.com/taoyds/test-suite-sql-eval)?

**Comment by Apricity-lxy** [comment]
Yes, I clone it from official repo.
Thank you.

**Comment by Apricity-lxy** [comment]
Thanks for your answer. There are some wrong with my database. Thank you!

**Comment by BeiwenZhang** [comment]
Hi，I had the same problem, could you please share your solution? I had used the last test suite
