### ISSUE TITLE
Error during data_preprocess

### ISSUE THREAD

**Issue by belugak** [BeachWang/DAIL-SQL#7]
Hello!

Thanks for great work! when I followed the instruction I got stuck when I ran the data_preprocess.py， it told me that 'Error while loading a tagger model (probably missing model file). Why did this situation occur? How to resolve this problem?

Thanks a lot!

**Comment by belugak** [comment]
also，my test section linking is 0%

**Comment by BeachWang** [comment]
Hi,

Have you launch the coreNLP server successfully?

**Comment by belugak** [comment]
> Hi,
> 
> Have you launch the coreNLP server successfully?

How can I tell that I lauch the coreNLP server successfully

**Comment by belugak** [comment]
It seems that I haven't lauch the coreNLP successfully, cause I found the 'Error: Could not find or load main class edu.stanford.nlp.pipeline.StanfordCoreNLPServer' in the nohup.out
But I followed the instruction in README, why I failed to lauch the server? And How can I resolve this problem?

Thanks for replying

**Comment by belugak** [comment]
I used 'curl http://localhost:9000' and I got a html page as return ,is that mean I lauch the server successfully?

**Comment by belugak** [comment]
Hi,
The problem above have been resolved but now I have new problem want to ask you. during prompt generation, we need a your_pre_generated_queries_file, but I don't know what is supported query type, could you please inform me ?
Thanks a lot.

**Comment by BeachWang** [comment]
Hi,

The `your_pre_generated_queries_file` contains 1034 lines of predicted SQL statements specifically generated for problems in the dev set. These predictions follow the same format as the `results/DAIL-SQL+GPT-4.txtfile`. In the DAIL-SQL framework, these predictions are the output of LLMs using EUCDISQUESTIONMASK selection. For more detailed information, please refer to the `run_dail_sql.shfile`. Additionally, it is also possible to use your own model to generate predictions for the dev set in advance. 


-----原始邮件-----
发件人:belugak 
发送时间:2023-10-27 10:44:42 (星期五)
收件人: BeachWang/DAIL-SQL 
抄送: BeachWang , Comment 
主题: Re: [BeachWang/DAIL-SQL] Error during data_preprocess (Issue #7)

Hi,
The problem above have been resolved but now I have new problem want to ask you. during prompt generation, we need a your_pre_generated_queries_file, but I don't know what is supported query type, could you please inform me ?
Thanks a lot.

**Comment by BeachWang** [comment]
Hi, 
We take [Graphix](https://github.com/AlibabaResearch/DAMO-ConvAI/tree/main/graphix) as our preliminary model in our experiments in the paper. We have upload the `your_pre_generated_queries_file` in `results/graphix_result.txt` for Spider dev.
