### ISSUE TITLE
How are foreign keys added to the schema?

### ISSUE THREAD

**Issue by wfel** [BeachWang/DAIL-SQL#9]
Hello,

I just read your work and find that you add foreign keys to `BS_p`, `OD_p`, `TR_p`, and `AS_p` prompt formats. I'm curious about these formats with foreign keys, but I can't find details of these formats in your paper. Did I missed something or could you just give some examples about these formats?

Thank you.

**Comment by BeachWang** [comment]
Hi,

You can refer to `TextWithForeignKeyPrompt`, `NumberSignWithForeignKeyPrompt`, `BaselinePrompt` and `InstructionWithForeignKeyPrompt` in `prompt/PromptReprTemplate.py` for details.
